=== ReadWriteLock
:description: Опис конструкції ReadWriteLock й робота з нею в java

Ідея що стоїть за цим механізмом блокування потоків полягає в тому щоб дозволити одночасне блокування ресурсу на читання потоками коли ресурс незаблокований на запис й блокувати будь-який інший доступ до ресурсу коли він заблокований на запис крім потоку який його заблокував.

Правила якими керується цей механізм наступні:

. Потік, який хоче заблокувати ресурс на читання, блокує його якщо він не заблокований на запис або коли інший потік очікує на блокування цього ресурсі на запис для себе.
. Потік, який хоче заблокувати ресурс на запис, блокує його якщо ресурс не заблокований ні на запис, ні на читання.

`java.util.concurrent.locks.ReadWriteLock` це інтрефейс.
В java 18 є його реалізація - клас `ReentrantReadWriteLock`.

.Приклад
[%collapsible%open]
====
.Приклад використання ReentrantReadWriteLock
[source,java,linenos]
----
include::ReentrantReadWriteLockExample.java[]
----

.Вивід консолі
[source,bash,linenos]
----
in read lock: readLockCount = 1 isWriteLocked = false [1]
in read lock: readLockCount = 2 isWriteLocked = false [1]          // <1>
in write lock: readLockCount = 0 isWriteLocked = true [1, 2]
in write lock: readLockCount = 0 isWriteLocked = true [1, 2, 3]    // <2>
in read lock: readLockCount = 1 isWriteLocked = false [1, 2, 3]
in write lock: readLockCount = 0 isWriteLocked = true [1, 2, 3, 4]
in read lock: readLockCount = 2 isWriteLocked = false [1, 2, 3, 4]
in read lock: readLockCount = 3 isWriteLocked = false [1, 2, 3, 4]
in read lock: readLockCount = 4 isWriteLocked = false [1, 2, 3, 4]
in read lock: readLockCount = 1 isWriteLocked = false [1, 2, 3, 4]
in read lock: readLockCount = 5 isWriteLocked = false [1, 2, 3, 4]
in read lock: readLockCount = 6 isWriteLocked = false [1, 2, 3, 4]
in read lock: readLockCount = 7 isWriteLocked = false [1, 2, 3, 4]
----
<1> Наявність декількох блокувань одночасно може бути лише при блокуванні для читання
<2> Блокування для запису може бути отримане тільки одне й лише тоді коли немає інших блокувань
====