=== Key-indexed count

Цей метод лежить в основі деяких алгоритмів сортування текстів, наприклад Least Significant Digit (LSD)- для сортування текстів однакової довжини, Most Significant Digit (MSD) - для сортування текстів довільної довжини.

Суть цього методу можна описати в таких кроках:

. Перетворити кожний елемент сортування (тобто те що сортується як єдине ціле, наприклад ціле слово абстрагуючись від літер з яких воно складається) в деякий індекс для покращення ефективності сортування
. Порахувати частоти кожного індексу у списку який потрібно відсортувати
. Використовуючи інформацію про частоти кожного індексу розрахувати для кожного з них позицію його першої появи в майбутньому відсортованому списку
. Розмістити в допоміжний список елементи оригінального списку на позиції відповідно до інформації про позиції перших появ кожного індексу
. Перезаписати оригінальний список відсортованим допоміжним списком

[bibliography]
==== Бібліографія

* [[[Algorithms, Algorithms 4th Edition by Robert Sedgewick and Kevin Wayne]]]