=== Метод Key-indexed counting

Цей метод лежить в основі деяких алгоритмів сортування текстів, наприклад Least Significant Digit (LSD)- для сортування текстів однакової довжини, Most Significant Digit (MSD) - для сортування текстів довільної довжини.

Суть цього методу можна описати в таких кроках:

. Перетворити кожний елемент сортування (тобто те що сортується як єдине ціле, наприклад ціле слово абстрагуючись від літер з яких воно складається) в деякий індекс для покращення ефективності сортування
. Порахувати частоти кожного індексу у списку який потрібно відсортувати
. Використовуючи інформацію про частоти кожного індексу розрахувати для кожного з них позицію його першої появи в майбутньому відсортованому списку
. Розмістити в допоміжний список елементи оригінального списку на позиції відповідно до інформації про позиції перших появ кожного індексу
. Перезаписати оригінальний список відсортованим допоміжним списком

Важливою властивістю цього методу є його *стабільність* - елементи сортування з однаковими індексами зберігають своє передування відносно один від одного у відсортованому списку.

.Приклад
[%collapsible%open]
====
.Приклад сортування методом Key-indexed counting
[source,java,linenos,%collapsible]
----
include::KeyIndexedCountingMethod.java[]
----

.Вивід консолі
[source,bash,linenos]
----
[0, 2, 2, 1, 2]
[0, 2, 4, 5, 7]
[[d, 1], [g, 1], [b, 2], [e, 2], [f, 3], [a, 4], [c, 4]]
[[d, 1], [g, 1], [b, 2], [e, 2], [f, 3], [a, 4], [c, 4]]
----
====

[bibliography]
==== Бібліографія

* [[[Algorithms, Algorithms 4th Edition by Robert Sedgewick and Kevin Wayne]]]