=== Метод Key-indexed counting

Цей метод лежить в основі деяких алгоритмів сортування текстів, наприклад Least Significant Digit (LSD)- для сортування текстів однакової довжини, Most Significant Digit (MSD) - для сортування текстів довільної довжини.

Суть цього методу можна описати в таких кроках:

. Перетворити кожний елемент сортування (тобто те що сортується як єдине ціле, наприклад ціле слово абстрагуючись від літер з яких воно складається) в деякий індекс для покращення ефективності сортування
. Порахувати частоти кожного індексу у списку який потрібно відсортувати
. Використовуючи інформацію про частоти кожного індексу розрахувати для кожного з них позицію його першої появи в майбутньому відсортованому списку
. Розмістити в допоміжний список елементи оригінального списку на позиції відповідно до інформації про позиції перших появ кожного індексу
. Перезаписати оригінальний список відсортованим допоміжним списком

Важливою властивістю цього методу є його *стабільність* - елементи сортування з однаковими індексами зберігають своє передування відносно один від одного у відсортованому списку.

.Приклад
[%collapsible%open]
====
.Приклад сортування методом Key-indexed count
[source,java,linenos,%collapsible]
----
include::KeyIndexedCountingMethod.java[]
----

.Вивід консолі
[source,bash,linenos]
----
[electric, electric, possible, continue, medicine, occasion, occasion, politics, industry, ceremony, heavenly]
[politics, electric, electric, possible, heavenly, medicine, ceremony, occasion, occasion, industry, continue]
[possible, politics, medicine, occasion, occasion, heavenly, continue, ceremony, electric, electric, industry]
[medicine, heavenly, possible, continue, ceremony, occasion, occasion, industry, politics, electric, electric]
[occasion, occasion, electric, electric, ceremony, medicine, politics, possible, continue, industry, heavenly]
[heavenly, occasion, occasion, medicine, industry, electric, electric, politics, continue, ceremony, possible]
[occasion, occasion, heavenly, medicine, ceremony, electric, electric, industry, politics, continue, possible]
[ceremony, continue, electric, electric, heavenly, industry, medicine, occasion, occasion, politics, possible]
----
====

[bibliography]
==== Бібліографія

* [[[Algorithms, Algorithms 4th Edition by Robert Sedgewick and Kevin Wayne]]]