=== Доведення гіпотез методом індукції

Цей метод складається з таких етапів:

.  перевірки справедливості виразу для базового випадку
.  перевірки справедливості індуктивної гіпотези - гіпотези що вираз також справедливий і для наступного (або в залежності від способу доведення - попереднього) числа

.Приклад
[%collapsible%open]
====
Довести справедливість виразу:

stem:[F(n) : ((n),(3))=(n(n-1)(n-2))/6] , для stem:[n>=3]

Переконаємося що цей вираз справджується для базового випадку:

stem:[F(3) : ((3),(3))=(3*2*1)/6 = 1]

Оскільки вираз справджується для базового випадку, то достатньо довести справедливість індуктивної гіпотези:

stem:[F(n + 1): ((n+1),(3))=((n+1)n(n-1))/6]

Нехає є множина:

stem:[X={1, 2, .., n+1 }]

Введемо множину:

stem:[Y=X - {n+1} = {1, 2, .. n}]

Отже:

stem:[ F(n+1) : |((X), (3))| =| ((Y), (3)) | + | ((Y), (2) ) | = ((n),(3)) + | ((Y), (2) ) | =  (n(n-1)(n-2))/6 + | ((Y), (2) ) |]

Доведемо що:

stem:[| ((Y), (2) ) | = ((n), (2)) = (n(n-1))/2]

Візьмемо за базовий випадок:

stem:[((2), (2)) = (2(2-1))/2 = 1]

Доведемо індуктивну гіпотезу:

stem:[| ((X), (2) ) | = ((n+1), (2)) = ((n+1)n)/2]

Ця гіпотеза справджується, оскільки:

stem:[| ((X), (2) ) | = | ((Y), (2) ) | + n = (n(n-1)+2n)/2 = (n^2+n)/2 = ((n+1)n)/2]

Тому:

stem:[F(n+1): (n(n-1)(n-2))/6 + | ((Y), (2) ) | = (n(n-1)(n-2))/6 + (n(n-1))/2 = (n(n-1)(n-2+3))/6 = ((n+1)n(n-1))/6]

Що й потрібно було довести.
====

[bibliography]
==== Бібліографія

* [[[ProgrammersIntroductionToMathematics, A Programmer’s Introduction to Mathematics by Jeremy Kun]]] https://pimbook.org/