=== Phaser

`java.util.concurrent.Phaser` узагальнює собою `java.util.concurrent.CountDownLatch` і `java.util.concurrent.CyclicBarrier`, а також має свої особливості оскільки під час його  роботи кількість його учасників (потоків) може змінюватися.
Отже, кількість учасників Phaser-а можна програмно реєструвати/знімати з реєстрації прямо під час його роботи.

Метод `Phaser.onAdvance` викликається при здійсненні фазового переходу (інкременту змінної phase) і його можна перевизначити для задавання умов за яких Phaser повинен закінчити роботу - для цього цей метод повинен повернути значення `true`.

`java.util.concurrent.Phaser` не зберігає інформацію про те які саме учасники зареєстровані, але можна реалізувати такий функціонал самому в своєму підкласі успадкованого від нього.
Виклики ж методів прибуття незареєстрованих учасників є помилкою і може призвести до викидання `IllegalStateException` при подальшій роботі з цим Phaser-ом.

Phaser-и також можна об'єднувати ( наприклад, в деревоподібні структури ) для зменшення змагальності великої кількості учасників за ресурси хоч при цьому й можуть бути великі накладні витрати на операцію.

.Приклад
[%collapsible%open]
====
.Приклад використання Phaser (за мотивом javadoc)
[source,java,linenos]
----
include::PhaserExp.java[]
----

.Вивід консолі
[source,bash,linenos]
----
-----alternativeToCountDownLatch------
before sleep
after sleep
t8 t3 t5 t0 t7 t2 t4 t6 t1 t9
-----recurrentBatchExecution------
0 : t0 t1 t2 t3 t4 t5 t6 t7 t8 t9
1 : t9 t8 t2 t6 t7 t5 t0 t1 t3 t4
2 : t5 t1 t6 t0 t8 t2 t3 t4 t9 t7
3 : t7 t4 t0 t2 t3 t8 t5 t9 t1 t6
4 : t6 t9 t5 t4 t1 t7 t8 t2 t3 t0
5 : end
----
====