=== Phaser

`java.util.concurrent.Phaser` узагальнює собою `java.util.concurrent.CountDownLatch` і `java.util.concurrent.CyclicBarrier`, а також має свої особливості оскільки під час його  роботи кількість його учасників (потоків) може змінюватися.
Отже, кількість учасників Phaser-а можна програмно реєструвати/знімати з реєстрації прямо під час його роботи.

Метод `Phaser.onAdvance` викликається при здійсненні фазового переходу (інкременту змінної phase) і його можна перевизначити для задавання умов за яких Phaser повинен закінчити роботу - для цього цей метод повинен повернути значення `true`.

`java.util.concurrent.Phaser` не зберігає інформацію про те які саме учасники зареєстровані, але можна реалізувати такий функціонал самому в своєму підкласі успадкованого від нього.
Виклики ж методів прибуття незареєстрованих учасників є помилкою і може призвести до викидання `IllegalStateException` при подальшій роботі з цим Phaser-ом.

Phaser-и також можна з'єднувати в деревоподібні структури для зменшення змагальності за ресурси великої кількості учасників.
Це може збільшити пропускну здатність хоч при цьому й можуть бути великі накладні витрати на кожну операцію.

.Приклад
[%collapsible%open]
====
.Приклад використання Phaser (за мотивом javadoc)
[source,java,linenos]
----
include::PhaserExample.java[]
----

.Вивід консолі
[source,bash,linenos]
----
-----alternativeToCountDownLatch------
before sleep
after sleep
t7 t5 t9 t2 t3 t6 t1 t8 t4 t0
-----recurrentBatchExecution------
0 : t0 t1 t2 t3 t4 t5 t6 t7 t8 t9
1 : t9 t7 t0 t2 t1 t8 t5 t4 t3 t6
2 : t6 t4 t8 t5 t3 t1 t2 t0 t9 t7
3 : t2 t0 t4 t7 t6 t3 t8 t9 t1 t5
4 : t5 t4 t7 t9 t1 t3 t2 t8 t6 t0
5 : end

-----buildTreeOfPhasers------
phase advancing 0
0 phaser.PhaserExample$3@11e28ba0[phase = 1 parties = 2 arrived = 0] 1 3
2 phaser.PhaserExample$3@46806c46[phase = 1 parties = 1 arrived = 0] 1 1
0 phaser.PhaserExample$3@11e28ba0[phase = 1 parties = 2 arrived = 0] 1 2
1 phaser.PhaserExample$3@356e93b6[phase = 1 parties = 2 arrived = 0] 1 4
1 phaser.PhaserExample$3@356e93b6[phase = 1 parties = 2 arrived = 0] 1 5
phase advancing 1
0 phaser.PhaserExample$3@11e28ba0[phase = 2 parties = 2 arrived = 0] 2 6
2 phaser.PhaserExample$3@46806c46[phase = 2 parties = 1 arrived = 0] 2 8
0 phaser.PhaserExample$3@11e28ba0[phase = 2 parties = 2 arrived = 0] 2 7
1 phaser.PhaserExample$3@356e93b6[phase = 2 parties = 2 arrived = 0] 2 9
1 phaser.PhaserExample$3@356e93b6[phase = 2 parties = 2 arrived = 0] 2 10
phase advancing 2
0 phaser.PhaserExample$3@11e28ba0[phase = -2147483645 parties = 2 arrived = 2] -2147483645 11
2 phaser.PhaserExample$3@46806c46[phase = -2147483645 parties = 1 arrived = 1] -2147483645 13
0 phaser.PhaserExample$3@11e28ba0[phase = -2147483645 parties = 2 arrived = 2] -2147483645 12
1 phaser.PhaserExample$3@356e93b6[phase = -2147483645 parties = 2 arrived = 2] -2147483645 14
1 phaser.PhaserExample$3@356e93b6[phase = -2147483645 parties = 2 arrived = 2] 3 15
----
====