name: GitHub Pages Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

  # Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install rouge
        run: sudo apt-get install -y ruby

      - name: install asciidoctor
        run: sudo gem install asciidoctor

      - name: install asciidoctor-multipage
        run: sudo gem install asciidoctor-multipage

      - name: install gnuplot
        run: sudo apt-get install -y gnuplot

      - name: install asciidoctor-diagram
        run: sudo gem install asciidoctor-diagram

      - name: install graphviz
        run: sudo apt install graphviz

#      - name: install pandoc
#        run: sudo apt install pandoc

#      - name: install lynx
#        run: sudo apt-get install lynx

      - name: run build script
        run: ./.github/scripts/entrypoint.sh
        shell: bash

      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  generate_sitemap:
    needs: build_and_deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1.8.0
        with:
          base-url-path: https://zakutok.github.io/

      - name: Output stats
        run: |
          echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
          echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
          echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

      - uses: stefanzweifel/git-auto-commit-action@v4

      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1